package billsplitter.ui;

import billsplitter.model.Group;
import billsplitter.service.DataStore;
import javax.swing.*;
import java.awt.*;

public class GroupListFrame extends JFrame {

    JPanel listPanel;
    Color BG = new Color(255, 240, 245);
    Color PINK_LIGHT = new Color(255, 240, 245);
    Color PINK_MED = new Color(255, 182, 193);
    Color PINK_STRONG = new Color(255, 105, 180);

    public GroupListFrame() {
        this(null);
    }

    // Constructor that accepts bounds to maintain window position
    public GroupListFrame(Rectangle bounds) {
        setTitle("Groups");
        setSize(400, 600);
        if (bounds != null) setBounds(bounds);
        else setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel main = new JPanel(new BorderLayout());
        main.setBackground(BG);

        // ➕ ADD BUTTON (TOP)
        JButton add = new JButton("+");
        styleTopButton(add);
        add.addActionListener(e -> {
            // Pass current bounds and DISPOSE this window
            new AddGroupFrame(this.getBounds()).setVisible(true);
            this.dispose(); 
        });

        listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        listPanel.setBackground(BG);

        refreshList();

        JScrollPane scroll = new JScrollPane(listPanel);
        scroll.setBorder(null);

        // 📜 HISTORY BUTTON (BOTTOM)
        JButton historyBtn = new JButton("View History");
        styleBottomButton(historyBtn);
        historyBtn.addActionListener(e -> {
            new HistoryFrame(this.getBounds()).setVisible(true);
            this.dispose();
        });

        main.add(add, BorderLayout.NORTH);
        main.add(scroll, BorderLayout.CENTER);
        main.add(historyBtn, BorderLayout.SOUTH);

        add(main);
    }

    public void refreshList() {
        listPanel.removeAll();
        for (int i = 0; i < DataStore.groups.size(); i++) {
            Group g = DataStore.groups.get(i);
            final int index = i; // Needed for the inner class

            String status = g.isSettled() ? " ✅" : " ❌";
            JButton btn = new JButton(g.getName() + status);
            btn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
            btn.setAlignmentX(Component.CENTER_ALIGNMENT);
            
            // Zebra Striping
            btn.setBackground(index % 2 == 0 ? PINK_LIGHT : Color.WHITE);
            btn.setForeground(Color.BLACK);
            btn.setFocusPainted(false);
            btn.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

            btn.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) { btn.setBackground(PINK_MED); }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btn.setBackground(index % 2 == 0 ? PINK_LIGHT : Color.WHITE);
                }
            });

            btn.addActionListener(e -> {
                new GroupDetailsFrame(g, this.getBounds()).setVisible(true);
                this.dispose();
            });

            listPanel.add(btn);
            listPanel.add(Box.createVerticalStrut(5));
        }
        listPanel.revalidate();
        listPanel.repaint();
    }

    private void styleTopButton(JButton btn) {
        btn.setBackground(PINK_STRONG);
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 18));
        btn.setPreferredSize(new Dimension(0, 50));
    }

    private void styleBottomButton(JButton btn) {
        btn.setBackground(PINK_MED);
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btn.setPreferredSize(new Dimension(0, 50));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       // try {
          //  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
           //     if ("Nimbus".equals(info.getName())) {
            //        javax.swing.UIManager.setLookAndFeel(info.getClassName());
           //         break;
              //  }
          //  }
      //  } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        //    logger.log(java.util.logging.Level.SEVERE, null, ex);
       // }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GroupListFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
